server:
  port: 8443
  ssl:
    enabled: true
    key-store: spring-boot-security-https/src/main/resources/mykeystore.p12
    key-store-password: 12345678
    key-store-type: PKCS12
    key-alias: myexamplekey